### ISSUE TITLE
Opinion/Question: Why using Java for tools?

### ISSUE THREAD

**Issue by raysan5** [Stephane-D/SGDK#129]
Hi, I've been following this project for long time, really like it despite not having enough time to use it extensively. Creating a Megadrive game is in my long TODO list. 

I've seen that lately you're relying on Java for some tools creation, specifically resourcemanager, my question is, why not use also C for tools creation? Java requires Java Runtime installation and, personally, I don't like it. Usually a Java app is also slower and more cumbersome than a simple C application.

I've created a simple and easy-to-use C library for apps/gamedev: [raylib](https://github.com/raysan5/raylib) (lightweight, multiplatform, no-external-dependencies, high-performant), also created [raygui](https://github.com/raysan5/raygui), intended for simple tools, and I think it could fit with your tooling.

I can take a look to resourcemanager and see if I can create some similar interface with raylib+raygui. Please, could you share some screenshots of resourcemanager (I can't find the binary)?

In any case, congrats for your amazing library! :)

**Comment by turiaso** [comment]
Hi Ray,

The decision to develop the tools in Java instead of in C has been fundamentally for 3 reasons:
- The programming in C 97 is a headache, xD, C # could have been considered.
- Java is cross-platform, we just have to make a compilation and a single version of the code.
- There are many third-party libraries that help with the treatment of images and sounds.

I hope to have solved your doubts.

Enjoy the new version of Resource Manager 0.4.0

Regards!
