### ISSUE TITLE
XGM crossfade support

### ISSUE THREAD

**Issue by doragasu** [Stephane-D/SGDK#155]
Would it be possible to add a function for the XGM driver to crossfade the sound output?

Just to avoid abrupt song changes ^_^

**Comment by Stephane-D** [comment]
Unfortunately it's not possible. XGM driver doesn't support volume modulation so there is no way to add that kind of feature. I plan to do a new XGM v2 driver adding that kind of functionality but honestly it's a big piece and that won't happen soon as it requires a complete rewrite (current XGM driver cannot really support new features due to the way it was designed)

**Comment by doragasu** [comment]
OK, I'm closing this then, and patiently waiting for that XDM v2 driver.

Thanks for the answer!
