### ISSUE TITLE
Missing VDPSpriteIndex on Sprite Struct

### ISSUE THREAD

**Issue by saintienn** [Stephane-D/SGDK#268]
Hi Stef!
I was starting to use some vdp functions to handle sprite size (VDP_setSpriteSize) and sprite position (VDP_setSpritePosition), but these functions require the VDP sprite index as a parameter, but in revision 5f958e0 it was removed from the sprite structure (I see the code, really a lot of cool improvements have been made), but I need how to get it another way. In the SPR_spriteEx function, a parameter to set spriteIndex is also no longer used.

thanx :)
Francis Fussiger

**Comment by Stephane-D** [comment]
Hi @saintienn 

Be careful, you're mixing the low level sprite API (vdp_spr.c, VDP_xxx methods) and the high level API (spr_eng.c, SPR_xxx methods), you cannot do that.
You should only use one of those at a time and generally you can always go through the high level API (SPR_xxx methods).
You're right that i removed the low hardware sprite index info from the high level API lately, because I wanted to simplify it and make it more efficient on hardware sprite usage. Also that sprite index info was almost never used on the high level API as we could simply use SPR_setDepth(..) to set inter sprite priority.

**Comment by saintienn** [comment]
Yes, I know mixing levels is not good practice, but the sprite size control (via VDP_setSpriteSize) I was using to create a visual effect in a context isolated from the sprite engine. I'm just creating a sprite using the high level of the api (with 1 frame) to get the index, then using the low level functions of the vps (without mixing with the high level). If there is any way to get this index, it would be great, because I can't change the sprite size at runtime by the high level api :)

**Comment by Stephane-D** [comment]
Given how i modified the sprite engine lately, there is no way to get the sprite index as the list is now fully rebuild at each frame. When i made the change I was afraid that some people may be using the sprite index to do some tricks with it but unfortunately the new method is much more efficient in sprite usage so i don't plan to come back with the old method.
The only method to get the sprite index would be to iterate over the sprite list and increment the index exactly as the SPR_update(..) method does but that would be time consuming as you need to do it at each frame (between the SPR_update(..)  and the SYS_doVBlankProcess() calls).

**Comment by saintienn** [comment]
Hi Stef, thanks for clarifying my doubts. Really sprite engine performance is better now. If I find an alternative that is lighter to implement, I'll let you know.

Thanks a lot :)
Francis

**Comment by Stephane-D** [comment]
Sorry for the change, i hope you can find a workaround for your trick !
