### ISSUE TITLE
Rescomp freeze for some sprite resource in compilation time

### ISSUE THREAD

**Issue by saintienn** [Stephane-D/SGDK#298]
Its very strange but happen for me. 
I believe it's a bug in the new sprite crop improvement

SPRITE spr_goku_spn0 "sprite/squatpunch01/p00.png" 10 10 FAST 0 NONE TILE FAST
![p00](https://github.com/Stephane-D/SGDK/assets/781338/ae9f9202-8c85-4e93-895d-6e75e2c5505b)

SPRITE spr_goku_ck1 "sprite/chargeki/ck01.png" 10 12 FAST 0 NONE TILE FAST
![ck01](https://github.com/Stephane-D/SGDK/assets/781338/6a07fd7e-d1ea-4bad-ab47-489394205ac5)

**Comment by Stephane-D** [comment]
Thanks for reporting, indeed this is due to some (stupids) recent changes, sorry for that !
It's fixed now. Also i suggest you to use "BALANCED MEDIUM" as last parameters for your sprites as "TILE FAST" really gives too many sprites (13 and 16 sprites versus 8 and 10 sprites). The tile number increase a bit but worth the gain on the number of hardware sprites imo.

**Comment by saintienn** [comment]
Thanks!! I will follow your tip
